// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SprintathonAPI.Data;

#nullable disable

namespace SprintathonAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230530165633_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SprintathonAPI.Models.IdNameBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdNameBases");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdNameBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SprintathonAPI.Models.IdNamePrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("IdNamePrices");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdNamePrice");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SprintathonAPI.Models.Garment", b =>
                {
                    b.HasBaseType("SprintathonAPI.Models.IdNameBase");

                    b.HasDiscriminator().HasValue("Garment");
                });

            modelBuilder.Entity("SprintathonAPI.Models.GarmentType", b =>
                {
                    b.HasBaseType("SprintathonAPI.Models.IdNameBase");

                    b.HasDiscriminator().HasValue("GarmentType");
                });

            modelBuilder.Entity("SprintathonAPI.Models.User", b =>
                {
                    b.HasBaseType("SprintathonAPI.Models.IdNameBase");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("SprintathonAPI.Models.Material", b =>
                {
                    b.HasBaseType("SprintathonAPI.Models.IdNamePrice");

                    b.HasDiscriminator().HasValue("Material");
                });

            modelBuilder.Entity("SprintathonAPI.Models.Service", b =>
                {
                    b.HasBaseType("SprintathonAPI.Models.IdNamePrice");

                    b.HasDiscriminator().HasValue("Service");
                });
#pragma warning restore 612, 618
        }
    }
}
